services:
  app:
    build: .
    container_name: app_dev
    ports:
      - '3000:3000'
      - '9229:9229' # Porta do debugger

    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      command: sh -c "pnpm prisma generate || true && node --inspect=0.0.0.0:9229 node_modules/next/dist/bin/next dev"
    volumes:
      - .:/app # monta o código local no container
      - /app/node_modules # evita conflito de node_modules
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: db_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
