# GitHub Actions: Build e deploy Node.js (Next.js) para Azure Web App - izombie
# Docs: https://github.com/Azure/webapps-deploy

name: Build and Deploy Node.js App to Azure Web App - izombie

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read  # Necessário para actions/checkout
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: https://izombie.azurewebsites.net
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Next.js app
        run: npm run build --if-present
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run tests
        run: npm run test --if-present
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            package.json
            package-lock.json
            .next
            public
            # inclua pastas de assets ou build necessários

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Necessário para JWT
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F7834BAF97948B1B71D3E1505FC989A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E09DED1EA9F43609BE6DB0BA9C8D50B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E9E7649F2AD14637B05F4E84B64E478B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'izombie'
          slot-name: 'Production'
          package: .

